Disable the modules API polyfill on latest Ember
ember-cli/ember-cli-htmlbars pull request #683
Opened 2021-03-16 22:30 UTC by pzuraq

Disables the modules API polyfill on the latest versions of Ember.

2021-03-17 13:59 UTC, rwjblue commented
```
not ok 7 Chrome 89.0 - [48 ms] - tests/integration/components/test-inline-precompile: template literal proposal works
    ---
        actual: >
            null
        stack: >
            ReferenceError: _emberComponentTemplateOnly is not defined
                at Object._callee5$ (http://localhost:7357/assets/tests.js:508:19)
                at tryCatch (http://localhost:7357/assets/vendor.js:411:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:685:22)
                at Generator.prototype.<computed> [as next] (http://localhost:7357/assets/vendor.js:444:21)
                at asyncGeneratorStep (http://localhost:7357/assets/tests.js:348:105)
                at _next (http://localhost:7357/assets/tests.js:350:196)
                at http://localhost:7357/assets/tests.js:350:366
                at new Promise (<anonymous>)
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:350:99)
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:549:25)
        message: >
            Promise rejected during "template literal proposal works": _emberComponentTemplateOnly is not defined
        negative: >
            false
        browser log: |
```

2021-03-17 14:13 UTC, pzuraq commented
Yeah, this PR is going to be dependent on

- https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/357
- https://github.com/babel/ember-cli-babel/pull/387

The first one is a fix that directly impacts the behavior of this addon, the second one is required in order to properly _test_ this addon with the intended behavior

2021-03-17 21:42 UTC, rwjblue requested changes

2021-03-17 21:42 UTC, rwjblue commented on lib/template-compiler-plugin.js
> +  constructor(inputTree, _options, requiresModuleApiPolyfill) {
Should probably default to `true` here. Otherwise, this is a breaking change.

2021-03-17 21:42 UTC, rwjblue commented on lib/colocated-babel-plugin.js
> +          if (addedImports[exportName]) return addedImports[exportName];
Doesn't this suffer from the same problem that https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/357 fixed?

Shouldn't this return a new identifier each time?

2021-03-17 21:42 UTC, rwjblue commented on lib/colocated-babel-plugin.js
> +          return addedImports[exportName];
Doesn't this suffer from the same problem that https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/357 fixed?

2021-03-17 21:51 UTC, rwjblue commented on node-tests/template_compiler_test.js
> +    it('invokes AST plugins', async function () {
thanks for using async/await here, I just haven't had a chance to clean these other co.wrap's up yet

2021-03-17 21:51 UTC, rwjblue commented on node-tests/template_compiler_test.js
> +      let tree = new TemplateCompiler(input.path(), htmlbarsOptions, true);
FWIW, adding `true` here is the thing I was referring to (as a breaking change). If you do `require('ember-cli-htmlbars')` the thing you get is the template compiler broccoli-plugin (for better or worse) which makes the constructor at least intimate API (but probably public).

2021-03-18 00:30 UTC, rwjblue approved these changes

2021-03-18 00:30 UTC, merged

2021-03-28 20:40 UTC, ef4 commented on lib/ember-addon-main.js
> +    let checker = new VersionChecker(this.parent).for('ember-source', 'npm');
I suspect this is broken in second-level or deeper addons. They're looking for ember-source in their parent only, but should be look at the top level project. Same kind of bug as https://github.com/babel/ember-cli-babel/pull/396